# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/randy/Downloads/GameFromScra(p)tch/src"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/randy/Downloads/GameFromScra(p)tch/src"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/randy/Downloads/GameFromScra(p)tch/src/CMakeFiles" "/home/randy/Downloads/GameFromScra(p)tch/src/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/randy/Downloads/GameFromScra(p)tch/src/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GameFromScrap

# Build rule for target.
GameFromScrap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GameFromScrap
.PHONY : GameFromScrap

# fast build rule for target.
GameFromScrap/fast:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/build
.PHONY : GameFromScrap/fast

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/Game.cpp.s
.PHONY : Game.cpp.s

Settings.o: Settings.cpp.o

.PHONY : Settings.o

# target to build an object file
Settings.cpp.o:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/Settings.cpp.o
.PHONY : Settings.cpp.o

Settings.i: Settings.cpp.i

.PHONY : Settings.i

# target to preprocess a source file
Settings.cpp.i:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/Settings.cpp.i
.PHONY : Settings.cpp.i

Settings.s: Settings.cpp.s

.PHONY : Settings.s

# target to generate assembly for a file
Settings.cpp.s:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/Settings.cpp.s
.PHONY : Settings.cpp.s

Stage.o: Stage.cpp.o

.PHONY : Stage.o

# target to build an object file
Stage.cpp.o:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/Stage.cpp.o
.PHONY : Stage.cpp.o

Stage.i: Stage.cpp.i

.PHONY : Stage.i

# target to preprocess a source file
Stage.cpp.i:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/Stage.cpp.i
.PHONY : Stage.cpp.i

Stage.s: Stage.cpp.s

.PHONY : Stage.s

# target to generate assembly for a file
Stage.cpp.s:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/Stage.cpp.s
.PHONY : Stage.cpp.s

Textures.o: Textures.cpp.o

.PHONY : Textures.o

# target to build an object file
Textures.cpp.o:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/Textures.cpp.o
.PHONY : Textures.cpp.o

Textures.i: Textures.cpp.i

.PHONY : Textures.i

# target to preprocess a source file
Textures.cpp.i:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/Textures.cpp.i
.PHONY : Textures.cpp.i

Textures.s: Textures.cpp.s

.PHONY : Textures.s

# target to generate assembly for a file
Textures.cpp.s:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/Textures.cpp.s
.PHONY : Textures.cpp.s

Timer.o: Timer.cpp.o

.PHONY : Timer.o

# target to build an object file
Timer.cpp.o:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/Timer.cpp.o
.PHONY : Timer.cpp.o

Timer.i: Timer.cpp.i

.PHONY : Timer.i

# target to preprocess a source file
Timer.cpp.i:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/Timer.cpp.i
.PHONY : Timer.cpp.i

Timer.s: Timer.cpp.s

.PHONY : Timer.s

# target to generate assembly for a file
Timer.cpp.s:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/Timer.cpp.s
.PHONY : Timer.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/GameFromScrap.dir/build.make CMakeFiles/GameFromScrap.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... GameFromScrap"
	@echo "... edit_cache"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... Settings.o"
	@echo "... Settings.i"
	@echo "... Settings.s"
	@echo "... Stage.o"
	@echo "... Stage.i"
	@echo "... Stage.s"
	@echo "... Textures.o"
	@echo "... Textures.i"
	@echo "... Textures.s"
	@echo "... Timer.o"
	@echo "... Timer.i"
	@echo "... Timer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

